/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiShopifyKitsRouteImport } from './routes/api/shopify-kits'
import { Route as ApiRecolorRouteImport } from './routes/api/recolor'

const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShopifyKitsRoute = ApiShopifyKitsRouteImport.update({
  id: '/api/shopify-kits',
  path: '/api/shopify-kits',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecolorRoute = ApiRecolorRouteImport.update({
  id: '/api/recolor',
  path: '/api/recolor',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/shop': typeof ShopRoute
  '/api/recolor': typeof ApiRecolorRoute
  '/api/shopify-kits': typeof ApiShopifyKitsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/shop': typeof ShopRoute
  '/api/recolor': typeof ApiRecolorRoute
  '/api/shopify-kits': typeof ApiShopifyKitsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/shop': typeof ShopRoute
  '/api/recolor': typeof ApiRecolorRoute
  '/api/shopify-kits': typeof ApiShopifyKitsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/shop' | '/api/recolor' | '/api/shopify-kits'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/shop' | '/api/recolor' | '/api/shopify-kits'
  id: '__root__' | '/' | '/shop' | '/api/recolor' | '/api/shopify-kits'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShopRoute: typeof ShopRoute
  ApiRecolorRoute: typeof ApiRecolorRoute
  ApiShopifyKitsRoute: typeof ApiShopifyKitsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shopify-kits': {
      id: '/api/shopify-kits'
      path: '/api/shopify-kits'
      fullPath: '/api/shopify-kits'
      preLoaderRoute: typeof ApiShopifyKitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recolor': {
      id: '/api/recolor'
      path: '/api/recolor'
      fullPath: '/api/recolor'
      preLoaderRoute: typeof ApiRecolorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShopRoute: ShopRoute,
  ApiRecolorRoute: ApiRecolorRoute,
  ApiShopifyKitsRoute: ApiShopifyKitsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
